public enum TokenType {
    // Literales
    INTEGER_LITERAL, FLOAT_LITERAL, STRING_LITERAL, CHAR_LITERAL,
    BOOLEAN_LITERAL, NULL_LITERAL,

    // Identificador
    IDENTIFIER,

    // Palabras clave
    ABSTRACT, BOOLEAN, BREAK, BYTE, CASE, CATCH, CHAR, CLASS,
    CONTINUE, DEFAULT, DO, DOUBLE, ELSE, EXTENDS, FINAL, FINALLY,
    FLOAT, FOR, IF, IMPLEMENTS, IMPORT, INSTANCEOF, INT, INTERFACE,
    LONG, NEW, PACKAGE, PRIVATE, PROTECTED, PUBLIC, RETURN, SHORT,
    STATIC, SUPER, SWITCH, THIS, THROW, THROWS, TRY, VOID, WHILE,

    // Operadores aritméticos
    PLUS, MINUS, STAR, SLASH, PERCENT,

    // Asignación
    ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, STAR_ASSIGN, SLASH_ASSIGN, PERCENT_ASSIGN,

    // Comparación
    EQUAL, NOT_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,

    // Lógicos
    AND, OR, NOT,

    // Incremento/decremento
    INCREMENT, DECREMENT,

    // Bitwise
    AMPERSAND, PIPE, CARET, TILDE, LEFT_SHIFT, RIGHT_SHIFT,

    // Delimitadores
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    SEMICOLON, COMMA, DOT, COLON, QUESTION,

    // Comentarios
    LINE_COMMENT, BLOCK_COMMENT,

    // Especiales
    EOF, UNKNOWN
}
